version: "3"

services:
  web: 
    container_name: logo_api
    restart: always
    build: .
    ports:
      - "9001:9000"
    links: 
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo_api_db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null